// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    var _this = this;

    this.initConfig({
      pkg: this.file.readJSON('package.json'),
      watch: {
        files: ['**/**.coffee', '**/*.scss'],
        tasks: ['default']
      },
      compass: {
        dist: {
          options: {
            config: 'config.rb',
            specify: ['css/src/screen.scss', 'css/src/ie.scss', 'css/src/print.scss']
          }
        }
      },
      jshint: {
        files: ['js/scripts.js'],
        options: {
          globals: {
            jQuery: true,
            console: true,
            module: true,
            document: true
          },
          force: true
        }
      },
      csslint: {
        options: {
          'star-property-hack': false,
          'duplicate-properties': false,
          'unique-headings': false,
          'ids': false,
          'display-property-grouping': false,
          'floats': false,
          'outline-none': false,
          force: true
        },
        src: ['css/*.css']
      },
      cssmin: {
        compress: {
          options: {
            banner: "/* Don't even attempt to edit this file */",
            report: 'min'
          },
          files: {
            'css/screen.min.css': ['css/screen.css'],
            'css/ie.min.css': ['css/ie.css'],
            'css/print.min.css': ['css/print.css']
          }
        }
      }
    });
    this.loadNpmTasks('grunt-contrib-compass');
    this.loadNpmTasks('grunt-contrib-jshint');
    this.loadNpmTasks('grunt-contrib-csslint');
    this.loadNpmTasks('grunt-contrib-cssmin');
    this.loadNpmTasks('grunt-contrib-watch');
    this.registerTask('default', ['jshint', 'compass']);
    this.registerTask('package', ['default', 'cssmin', 'csslint']);
    return this.event.on('watch', function(action, filepath) {
      return _this.log.writeln(filepath + ' has ' + action);
    });
  };

}).call(this);
